codeit-project-9/taskify

api/apiTypes/authType.ts
api/apiTypes/cardType.ts
api/apiTypes/columnsType.ts
api/apiTypes/commentsType.ts
api/apiTypes/dashboardsType.ts
api/apiTypes/invitationsType.ts
api/apiTypes/membersType.ts
api/apiTypes/userType.ts
tailwind.config.ts

feat: 테일윈드 색 및 api타입 추가

---

src/app/components/DashboardHeaderInSettings.tsx
src/app/components/InvitedDashboarList.tsx
src/app/components/InvitedDashboardListMobile.tsx
src/app/components/UpdateDashboardName.tsx
src/app/components/modals/NewDashboardModal.tsx

Image 컴포넌트에 width, height 를 추가하지 않아 오류가 발생했습니다.
관련 내용 추가하여 다시 push 하겠습니다!

fix: Image 컴포넌트에 width, height 추가

---

package-lock.json
package.json
src/app/components/DashbaordCard.tsx
src/app/components/DashboardList.tsx
src/app/components/InvitedDashboarList.tsx
src/app/components/modals/CommonModal.tsx
src/app/components/modals/Modal.tsx
src/app/components/modals/ModalExample.tsx
src/app/components/modals/NewDashboardModal.tsx
src/app/components/modals/UpdateColumnModal.tsx
src/app/components/ui/label.tsx
src/app/layout.tsx
src/app/mydashboard/page.tsx
src/components/ui/label.tsx
src/context/ModalContext.tsx

+ 버튼, 새로운 대시보드 버튼 클릭 시 새로운 대시보드 생성 모달이 뜨도록 하는 기능 구현하였습니다.

fix: + 버튼 클릭 시 새로운 대시보드 생성 모달이 뜨도록 하는 기능 구현

---

src/app/components/Column.tsx
src/app/components/ColumnCard.tsx
src/app/components/Comment.tsx
src/app/components/CommentsList.tsx
src/app/components/CustomAvatar.tsx
src/app/dashboard/[dashboardid]/page.tsx

- 가로 스크롤이 가능하게 수정하였습니다.
- 커스텀 아바타 랜덤 색깔 기능 구현하였습니다.
- 대시포드 컬럼 데이터 매핑/ 컬럼 생성 api구현하였습니다. ( 중복 컬럼 이름 경고 기능 제외 )
- 태블릿 크키 부터 컬럼 추가하기 버튼을 화면 하단에 fixed로 구현하였습니다

Feat: 반응형 구현 및, ColumnAPI연결

---

src/app/(dashboard)/dashboard/[dashboardid]/page.tsx

chore: 사라진 대시보드 페이지 복구

---

next.config.mjs
src/app/(dashboard)/dashboard/[dashboardid]/edit/page.tsx
src/app/(dashboard)/layout.tsx
src/app/api/apiTypes/dashboardsType.ts
src/app/components/Button.tsx
src/app/components/DashboardHeaderInSettings.tsx
src/app/components/DeleteButton.tsx
src/app/components/InvitationList.tsx
src/app/components/MemberList.tsx
src/app/components/PasswordChangeForm.tsx
src/app/components/ProfileSetting.tsx
src/app/components/SideBar.tsx
src/app/components/modals/SettingChangedModal.tsx

프로필 설정 기능과 대시보드 설정 페이지 api 연결은 얼추 끝났습니다.
프로필 사진이 있는 경우 바로 띄우도록 했습니다.
비밀번호 시 로그아웃이 되며 랜딩페이지로 이동합니다.
멤버 삭제 기능
초대 취소 기능

feat: 멤버삭제 및 초대 취소 기능 구현 및 프로필 설정 및 비밀번호 변경 기능 구현

---

src/app/(dashboard)/dashboard/[dashboardid]/page.tsx
src/app/components/Column.tsx
src/app/components/ModalFooterButtons.tsx
src/app/components/ModalInput.tsx
src/app/components/ToDoCardModal/CommentInput.tsx
src/app/components/ToDoCardModal/api.tsx
src/app/components/modals/DeleteColumnAlertModal.tsx
src/app/components/modals/NewColumnModal.tsx
src/app/components/modals/UpdateColumnModal.tsx

[ DeleteColumnAlertModal ]
- 컬럼 삭제 시 경고 문구 모달 생성 하였습니다
[ ModalFooterButtons, ModalInput ]
- 모달에 공통적으로 들어가는 버튼과 인풋을 컴포넌트로 분리하였습니다.
[ UpdateColumnModal ]
- 칼럼 수정하기 기능 구현하였습니다
- 칼럼 삭제하기 기능 구현하였습니다
- 칼럼 수정시에 변경 사항 없을 시 버튼 비활성화 되게 구현하였습니다.    
[api.tsx]
- 에러처리문 추가
<br>
- 컬럼 이름 중복 체크 구현
- 수정/삭제/생성이 불규칙적으로 성공하고 실패합니다. 에러는 나지 않는데 원인을 모르겠습니다.

Feat: 컬럼 수정, 삭제, 생성 기능 부분  완성 (오류미해결)

---

src/app/components/DashboardHeaderInSettings.tsx
src/app/components/InvitationList.tsx
src/app/components/InvitedDashboarList.tsx
src/app/components/UpdateDashboardName.tsx

1. 검색 기능 구현 완료했습니다.
~~2. 무한 스크롤은 내일 중으로 구현 완료할 것 같습니다.~~ => 구현 완료했습니다~!
3. 내가 만든 대시보드가 아닌데도 왕관이 붙는 기능 수정 완료했습니다.
4. 대시보드 설정페이지에서 '비브리지' 하드코딩 부분을 api 연동하여 수정했습니다. => 헤더, 사이드바 부분은 새로고침해야 바뀌어서 이 부분은 어떻게 관리하면 좋을지 얘기해보면 좋을 것 같습니다..!
5. 대시보드 설정페이지에서 초대하기 부분 구현 완료했습니다.

feat: 초대받은 대시보드 검색 기능 구현

---

src/app/components/Column.tsx
src/app/components/Inputs/AssigneeInput.tsx
src/app/components/Inputs/DescriptionInput.tsx
src/app/components/Inputs/DueDateInput.tsx
src/app/components/Inputs/ImageInput.tsx
src/app/components/Inputs/InputTypes.ts
src/app/components/Inputs/StateInput.tsx
src/app/components/Inputs/TagsInput.tsx
src/app/components/Inputs/TitleInput.tsx
src/app/components/LoginForm.tsx
src/app/components/SignupForm.tsx
src/app/components/modals/CreateCardForm.tsx
src/app/components/modals/EditCardForm.tsx
src/app/components/modals/EditCardModal.tsx
src/app/components/modals/SignupDoneModal.tsx
src/app/components/modals/ToDoCardModal.tsx
src/app/globals.css
src/app/page.tsx

할 일 수정 모달 완성
단, api이 실제로 잘 작동하는지는 확인요망

할 일 수정 모달 완성

---

src/app/components/DashboardHeader.tsx
src/app/components/DashboardHeaderInSettings.tsx
src/app/components/Inputs/DueDateInput.tsx
src/app/components/InvitedDashboarList.tsx
src/app/components/InvitedDashboardListMobile.tsx
src/app/components/modals/CreateCardForm.tsx

fix: 대시보드 헤더 레이아웃 수정

---

src/app/components/DashboardHeader.tsx
src/app/components/DashboardHeaderInSettings.tsx
src/context/InvitationDataContext.tsx

이제 dashboardId가 바뀔 때마다 초대내역 컨텍스트가 업데이트되도록 설정하였습니다.

fix: 초대내역 컨텍스트 업데이트 안되는 문제 해결

---

src/app/components/DashboardHeader.tsx
src/app/components/DashboardHeaderInSettings.tsx
src/app/components/InvitedDashboarList.tsx
src/app/components/InvitedDashboardListMobile.tsx
src/app/components/ToDoCardModal/CommentsList.tsx

'fix: 모바일 반응형 레이아웃 수정'

---

src/app/components/Inputs/AssigneeInput.tsx
src/app/components/Inputs/DescriptionInput.tsx
src/app/components/Inputs/DueDateInput.tsx
src/app/components/Inputs/ImageInput.tsx
src/app/components/Inputs/InputTypes.ts
src/app/components/Inputs/StateInput.tsx
src/app/components/Inputs/TagsInput.tsx
src/app/components/Inputs/TitleInput.tsx
src/app/components/modals/CreateCardForm.tsx
src/app/components/modals/EditCardForm.tsx
src/app/components/modals/ToDoCardModal.tsx

초기값을 불러오는 오류를 수정했습니다.
추가로 customAvatar로 교체했습니다.

fix: 수정 모달 초기값 불러오기 오류 수정

---

src/app/(dashboard)/dashboard/[dashboardid]/page.tsx
src/app/components/Column.tsx
src/app/components/ColumnCard.tsx
src/app/components/Inputs/DescriptionInput.tsx
src/app/components/Inputs/StateInput.tsx
src/app/components/Inputs/TitleInput.tsx
src/app/components/ToDoCardModal/CardContents.tsx
src/app/components/ToDoCardModal/CardHeader.tsx
src/app/components/ToDoCardModal/Comment.tsx
src/app/components/ToDoCardModal/CommentInput.tsx
src/app/components/ToDoCardModal/CommentsList.tsx
src/app/components/ToDoCardModal/ToDoCardDropDown.tsx
src/app/components/ToDoCardModal/util.tsx
src/app/components/modals/CreateCardForm.tsx
src/app/components/modals/DeleteCardModal.tsx
src/app/components/modals/DeleteColumnAlertModal.tsx
src/app/components/modals/EditCardForm.tsx
src/app/components/modals/ToDoCardModal.tsx
src/app/components/modals/UpdateColumnModal.tsx
src/app/layout.tsx
src/context/DashBoardIdContext.tsx

Feat: 카드 수정하기editCard 모달 연결

---

src/app/components/Inputs/DueDateInput.tsx
src/app/components/Inputs/StateInput.tsx
src/app/components/modals/CreateCardForm.tsx
src/app/components/modals/EditCardForm.tsx

이제 상태를 선택하면 피그마 시안처럼 보여지게 됩니다.
수정할 때 변경사항이 있고, 빈 칸이 없어야지만 버튼이 활성화됩니다.

fix: 할 일 수정 모달 버튼 활성화 조건 추가 및 시안 스타일 적용

---

src/app/(dashboard)/dashboard/[dashboardid]/page.tsx
src/app/components/Column.tsx
src/app/components/ColumnCard.tsx
src/app/components/CustomAvatar.tsx
src/app/components/ModalInput.tsx
src/app/components/ToDoCardModal/CardContents.tsx
src/app/components/ToDoCardModal/CardHeader.tsx
src/app/components/ToDoCardModal/CardInfo.tsx
src/app/components/ToDoCardModal/Comment.tsx
src/app/components/ToDoCardModal/CommentsList.tsx
src/app/components/ToDoCardModal/ToDoCardDropDown.tsx
src/app/components/modals/EditCardForm.tsx
src/app/components/modals/NewColumnModal.tsx
src/app/components/modals/UpdateColumnModal.tsx

- 카드만 스크롤되게 수정하였습니다
- 새로운 컬럼 생성 에러 스타일 처리하였습니다
- 갖종 overflow처리 완료.
- customavatar min-h추가, 이미지 추가시 기본 배경화면 흰색 추가
- 드롭다운 영역 밖 클릭하면 닫치는 기능 추가

Fix: dashboard페이지 스타일 수정

---

src/app/components/DashboardHeader.tsx
src/app/components/DashboardHeaderInSettings.tsx
src/app/components/InvitedDashboarList.tsx
src/context/DashBoardIdContext.tsx

1. hover 했을 경우 대시보드의 구성원 리스트를 볼 수 있는 기능을 추가했습니다.
2. DashboardHeaderInSettings 컴포넌트에 마이페이지로 갈 수 있는 기능을 추가했습니다.
3. 기타 레이아웃을 약간 수정했습니다.

feat: hover 시 대시보드 구성원 리스트 볼 수 있는 기능 추가

---

src/app/components/SignupForm.tsx
src/app/components/modals/EditCardForm.tsx
src/app/page.tsx

fix: 버그 수정

---

src/app/(dashboard)/dashboard/[dashboardid]/edit/page.tsx
src/app/(dashboard)/dashboard/[dashboardid]/page.tsx

fix: 컴포넌트 첫 글자 대문자로 수정

---

src/app/components/modals/EditCardForm.tsx

fix: 할 일 수정 모달 버튼 활성화 오류 수정

---

src/app/components/modals/InvitationModal.tsx
src/app/components/modals/NewDashboardModal.tsx

fix: 대시보드 생성, 초대하기 시 input 이 없는 경우 버튼 disabled
